#!/usr/bin/env bats

load setup

setup_file() {
    export FAKE_GOINFRE="${BATS_TMPDIR}/fake_goinfre"
    # PROJECT_ROOT is loaded from setup.bash, so we don't define TEST_LOCAL_ENV here 
    # until after setup() runs. We'll define it dynamically in the test.
}

teardown_file() {
    rm -rf "$FAKE_GOINFRE"
}

@test "Storage: init-env must configure VirtualBox and create local_env.sh reference" {
    export TEST_LOCAL_ENV="${PROJECT_ROOT}/config/local_env.sh"
    mkdir -p "$FAKE_GOINFRE"
    
    # Create the VBoxManage Mock in the directory generated by setup.bash
    echo '#!/bin/bash' > "${MOCK_BIN_DIR}/VBoxManage"
    echo 'echo "Mock VBoxManage executed successfully: $*" >> "'"${MOCK_BIN_DIR}/vbox_history.log"'"' >> "${MOCK_BIN_DIR}/VBoxManage"
    chmod +x "${MOCK_BIN_DIR}/VBoxManage"

    # Simulation of interactive prompt responses using a HereDoc/String
    # 1. Option 3 (Custom path)
    # 2. The FAKE_GOINFRE path
    # 3. The username dev_user
    run bash -c "${PROJECT_ROOT}/scripts/init-env.sh <<< $'3\n${FAKE_GOINFRE}\ndev_user\n'"
    
    [ "$status" -eq 0 ]
    
    # 1. Check that the VirtualBox wrapper was invoked with correct flags
    run cat "${MOCK_BIN_DIR}/vbox_history.log"
    [[ "$output" == *"setproperty machinefolder ${FAKE_GOINFRE}"* ]]
    
    # 2. Check that the local persistence artifact was generated correctly
    [ -f "$TEST_LOCAL_ENV" ]
    
    run grep "export DEVPOD_ROOT=\"${FAKE_GOINFRE}\"" "$TEST_LOCAL_ENV"
    [ "$status" -eq 0 ]
    
    run grep "export ADMIN_USER=\"dev_user\"" "$TEST_LOCAL_ENV"
    [ "$status" -eq 0 ]
    
    # Local cleanup
    rm -f "$TEST_LOCAL_ENV"
}
