#!/bin/bash
# =============================================================================
# scripts/init-env.sh – DevPod Initial Configuration Setup
# Purpose: Allow the user to specify custom paths (like 42 campus /goinfre)
#          before creating the base template.
# =============================================================================

set -e

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# We use the built-in ui_select from config.sh, but we need some basic colors first
# in case config.sh is not fully loaded.
C_CYAN='\033[1;36m'
C_BOLD='\033[1m'
C_RESET='\033[0m'
C_GREEN='\033[1;32m'
C_BLUE='\033[1;34m'
C_YELLOW='\033[1;33m'

clear
printf "${C_CYAN}${C_BOLD}🚀 DevPod Initial Setup${C_RESET}\n"
printf "${C_BLUE}Let's configure where DevPod stores your VMs and ISOs.${C_RESET}\n"
printf "${C_YELLOW}This is especially useful for 42 Campus (to use /goinfre or /sgoinfre).${C_RESET}\n\n"

# A basic select if we don't want to rely on ui_select before config is generated
echo "Select the storage location:"
echo "1) User Home (~/.devpod) [Default]"
echo "2) Current Directory ($PROJECT_ROOT/.devpod-data)"
echo "3) Custom Path (e.g. /goinfre/$USER/devpod)"
read -p "Enter choice [1-3]: " choice

case $choice in
    2)
        CUSTOM_PATH="$PROJECT_ROOT/.devpod-data"
        ;;
    3)
        read -p "Enter absolute path: " CUSTOM_PATH
        ;;
    *)
        CUSTOM_PATH="$HOME/.devpod"
        ;;
esac

# Ensure clean path
CUSTOM_PATH=$(echo "$CUSTOM_PATH" | tr -d '\r' | sed 's:/*$::')

echo ""
read -p "What username do you want for the VM? [$USER]: " VM_USERNAME
VM_USERNAME=${VM_USERNAME:-$USER}
VM_USERNAME=$(echo "$VM_USERNAME" | tr -d '\r')

# Write to local_env.sh
LOCAL_ENV="${PROJECT_ROOT}/config/local_env.sh"
cat <<EOF > "$LOCAL_ENV"
# Generated by make init
export DEVPOD_ROOT="$CUSTOM_PATH"
export ADMIN_USER="$VM_USERNAME"
EOF

printf "\n${C_GREEN}✔ Configuration saved!${C_RESET}\n"
printf "  - VMs will be stored in: $CUSTOM_PATH\n"
printf "  - VM Main User: $VM_USERNAME\n\n"
printf "You can now run: ${C_BOLD}make template${C_RESET}\n"
