#!/bin/bash
# =============================================================================
# scripts/wizard.sh – DevPod Interactive Wizard
# Purpose: Guide the user through VM creation with a Vite-like CLI experience.
# =============================================================================

set -e

# Get project root and source config
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${PROJECT_ROOT}/config/config.sh"

# -----------------------------------------------------------------------------
# 1. Welcome Message
# -----------------------------------------------------------------------------
clear
printf "${C_CYAN}${C_BOLD}🚀 DevPod Interactive Wizard${C_RESET}\n"
printf "${C_BLUE}Let's set up your development environment.${C_RESET}\n\n"

# -----------------------------------------------------------------------------
# 2. VM Name (ui_input)
# -----------------------------------------------------------------------------
ui_input "What is the name of your VM?" "devpod-vm"
VM_NAME=$(echo "$UI_INPUT_RESULT" | tr -d '\r')

# -----------------------------------------------------------------------------
# 3. OS Selection (ui_select)
# -----------------------------------------------------------------------------
OS_OPTIONS=("Ubuntu 24.04 LTS (Recommended)" "Debian 12/13")
ui_select "Select an Operating System:" "${OS_OPTIONS[@]}"
SELECTED_OS="${OS_OPTIONS[$UI_SELECT_RESULT]}"

if [[ "$UI_SELECT_RESULT" -eq 1 ]]; then
    SELECTED_DISTRO="debian"
else
    SELECTED_DISTRO="ubuntu"
fi
SELECTED_DISTRO=$(echo "$SELECTED_DISTRO" | tr -d '\r')

# -----------------------------------------------------------------------------
# 4. Resource Profile (ui_select)
# -----------------------------------------------------------------------------
PROFILE_LABELS=("Small  (2GB RAM, 1 CPU)" "Medium (4GB RAM, 2 CPU)" "Large  (8GB RAM, 4 CPU)")
PROFILE_DATA=("2048:1" "4096:2" "8192:4")

ui_select "Choose a resource profile:" "${PROFILE_LABELS[@]}"
SELECTED_PROFILE=$(echo "${PROFILE_DATA[$UI_SELECT_RESULT]}" | tr -d '\r')

# Extract RAM and CPU from profile
VM_RAM="${SELECTED_PROFILE%%:*}"
VM_CPU="${SELECTED_PROFILE##*:}"

# -----------------------------------------------------------------------------
# 5. Summary & Confirmation
# -----------------------------------------------------------------------------
printf "\n${C_CYAN}=== Configuration Summary ===${C_RESET}\n"
printf "  ${C_BOLD}VM Name:${C_RESET}   $VM_NAME\n"
printf "  ${C_BOLD}OS:${C_RESET}        $SELECTED_OS\n"
printf "  ${C_BOLD}Resources:${C_RESET} $VM_RAM MB RAM, $VM_CPU CPU(s)\n"
printf "${C_CYAN}=============================${C_RESET}\n\n"

CONFIRM_OPTIONS=("Yes, create it!" "No, start over" "Cancel")
ui_select "Does this look correct?" "${CONFIRM_OPTIONS[@]}"

case "$UI_SELECT_RESULT" in
    0)
        success "Great! Generating configuration..."
        
        # Clean variables of any potential \r
        VM_NAME=$(echo "$VM_NAME" | tr -d '\r')
        SELECTED_DISTRO=$(echo "$SELECTED_DISTRO" | tr -d '\r')
        VM_RAM=$(echo "$VM_RAM" | tr -d '\r')
        VM_CPU=$(echo "$VM_CPU" | tr -d '\r')

        # Create temporary config file
        WIZARD_CONFIG="${PROJECT_ROOT}/config/wizard_config.sh"
        cat <<EOF > "$WIZARD_CONFIG"
#!/bin/bash
# Generated by DevPod Wizard on $(date)
export SELECTED_DISTRO="$SELECTED_DISTRO"
export TEMPLATE_NAME="$VM_NAME"
export TEMPLATE_HOSTNAME="$VM_NAME"
export TEMPLATE_RAM_MB="$VM_RAM"
export TEMPLATE_CPU="$VM_CPU"
EOF
        
        info "Configuration saved to config/wizard_config.sh"
        success "Starting VM creation process (make template)..."
        
        # Run the actual creation
        if make -C "$PROJECT_ROOT" template; then
            success "VM '$VM_NAME' created successfully!"
            # We keep the config if successful, or delete it? 
            # Better delete it to avoid side effects on next 'make' calls
            rm "$WIZARD_CONFIG"
        else
            error "VM creation failed. Check the logs."
            rm "$WIZARD_CONFIG"
            exit 1
        fi
        ;;
    1)
        warn "Starting over..."
        exec "$0"
        ;;
    *)
        info "Operation cancelled."
        exit 0
        ;;
esac
