name: CI Pipeline - Validation & Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  shellcheck:
    name: Code Quality & Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Bats-core
        run: sudo apt-get update && sudo apt-get install -y bats

      - name: Run ShellCheck (SAST)
        uses: ludeeus/action-shellcheck@master
        with:
          # We check all .sh files in the repository
          scandir: '.'

      - name: Run Integration Tests
        run: make test
